[package]
name = "rusty_libimobiledevice"
version = "0.2.3"
edition = "2021"
authors = ["Jackson Coxson"]
description = "An ergonomic library to communicate with iOS devices"
homepage = "https://github.com/jkcoxson/rusty_libimobiledevice"
repository = "https://github.com/jkcoxson/rusty_libimobiledevice"
license = "LGPL-2.1-or-later"
keywords = ["libimobiledevice", "ios", "lockdown", "developer-tools"]
readme = "README.md"
documentation = "https://docs.rs/rusty_libimobiledevice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.14"
plist_plus = { version = "0.2.*" }
openssl = { version = "0.10.38", optional = true }
log = "0.4.15"

rcgen = { version = "0.13.2", features = ["x509-parser"] }
rsa = "0.9.8"
spki = "0.7.3"
openssl-src = "300.5.1"
# rustls-connector = { version = "0.21.7", features = ["rustls--aws_lc_rs"] }
aws-lc-rs = { version = "1.13.1" }
pem = "3.0.5"
rustls = { version = "0.23.28", features = ["aws_lc_rs", "tls12"] }

rustls-pki-types = "1.12.0"

x509-parser = "0.16.0"
x509-verify = { version = "0.4.8", features = ["sha1", "rsa", "std"] }
x509-cert = "0.2.5"


[build-dependencies]
bindgen = "0.59.2"
cc = "1.0.73"
cmake = "0.1.48"

[features]
pls-generate = []
dynamic = ["plist_plus/dynamic"]
static = ["plist_plus/static"]
vendored = ["plist_plus/vendored"]

[patch.crates-io]
plist_plus = { path = "../plist_plus" }